### Get All Reviews
GET http://localhost:3000/api/reviews?page=0&limit=5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY0MmY5YTRjLWQ4ZTUtNDA0OS1hMzRkLTFmOWMzNDVlMWMwZCIsInVzZXJUeXBlIjoiYWRtaW4iLCJpYXQiOjE3ODkyNTQ0ODEsImV4cCI6MTc5NDQzODQ4MX0.9Mn-vFvIpkmwrFgvGwrlHvQ92cFeZ7g0xjIG0FZus-I
### Get Single Review
GET http://localhost:3000/api/reviews/1


### Create New Review
POST http://localhost:3000/api/reviews/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY0MmY5YTRjLWQ4ZTUtNDA0OS1hMzRkLTFmOWMzNDVlMWMwZCIsInVzZXJUeXBlIjoiYWRtaW4iLCJpYXQiOjE3ODkyNTQ0ODEsImV4cCI6MTc5NDQzODQ4MX0.9Mn-vFvIpkmwrFgvGwrlHvQ92cFeZ7g0xjIG0FZus-I


{
    "comment": "this is a review",
    "rating": 4
   
}


//### Update Review
PATCH http://localhost:3000/api/reviews/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY0MmY5YTRjLWQ4ZTUtNDA0OS1hMzRkLTFmOWMzNDVlMWMwZCIsInVzZXJUeXBlIjoiYWRtaW4iLCJpYXQiOjE3ODkyNTQ0ODEsImV4cCI6MTc5NDQzODQ4MX0.9Mn-vFvIpkmwrFgvGwrlHvQ92cFeZ7g0xjIG0FZus-I

{
    "comment": "this is an updated review",
    "rating": 5
}


### Delete Review
DELETE http://localhost:3000/api/reviews/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY0MmY5YTRjLWQ4ZTUtNDA0OS1hMzRkLTFmOWMzNDVlMWMwZCIsInVzZXJUeXBlIjoiYWRtaW4iLCJpYXQiOjE3ODkyNTQ0ODEsImV4cCI6MTc5NDQzODQ4MX0.9Mn-vFvIpkmwrFgvGwrlHvQ92cFeZ7g0xjIG0FZus-I
